//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string Dept { get; set; }
        public string Desg { get; set; }
        public decimal Salary { get; set; }
        public Nullable<int> projid { get; set; }
        public string password { get; set; }
    
        public virtual ProjectInfo ProjectInfo { get; set; }
    }
}
