//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public ProjectInfo()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int projid { get; set; }
        public string projname { get; set; }
        public string domain { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
